pub fn get_mime_type(path: &str) -> String {
    let mime_type = match path {
        path if path.ends_with(".css") => "text/css",
        path if path.ends_with(".html") => "text/html",
        path if path.ends_with(".js") => "text/javascript",
        path if path.ends_with(".json") => "application/json",
        path if path.ends_with(".png") => "image/png",
        path if path.ends_with(".jpg") => "image/jpeg",
        path if path.ends_with(".jpeg") => "image/jpeg",
        path if path.ends_with(".gif") => "image/gif",
        path if path.ends_with(".svg") => "image/svg+xml",
        path if path.ends_with(".ico") => "image/x-icon",
        path if path.ends_with(".mp4") => "video/mp4",
        path if path.ends_with(".webm") => "video/webm",
        path if path.ends_with(".ogg") => "video/ogg",
        path if path.ends_with(".mp3") => "audio/mpeg",
        path if path.ends_with(".wav") => "audio/wav",
        path if path.ends_with(".flac") => "audio/flac",
        path if path.ends_with(".txt") => "text/plain",
        path if path.ends_with(".pdf") => "application/pdf",
        path if path.ends_with(".doc") => "application/msword",
        path if path.ends_with(".zip") => "application/zip",
        path if path.ends_with(".tar") => "application/x-tar",
        path if path.ends_with(".gz") => "application/gzip",
        path if path.ends_with(".bz2") => "application/x-bzip2",
        path if path.ends_with(".rar") => "application/vnd.rar",
        path if path.ends_with(".7z") => "application/x-7z-compressed",
        path if path.ends_with(".exe") => "application/x-msdownload",
        path if path.ends_with(".apk") => "application/vnd.android.package-archive",
        path if path.ends_with(".deb") => "application/x-deb",
        path if path.ends_with(".rpm") => "application/x-rpm",
        path if path.ends_with(".xml") => "application/xml",
        path if path.ends_with(".csv") => "text/csv",
        path if path.ends_with(".ini") => "text/plain",
        path if path.ends_with(".yml") => "text/plain",
        path if path.ends_with(".yaml") => "text/plain",
        path if path.ends_with(".toml") => "text/plain",
        _ => "*/*",
    };
    mime_type.to_string()
}
